### ISSUE TITLE
Tweak needed to eliminate PHP Warning

### ISSUE THREAD

**Issue by guyfugacity** [3ilogiclms/moodle-block_course_status_tracker#5]
Am getting the following warning after enabling the module in Moodle 2.8.6

> Notice: Undefined property: stdClass::$text in /var/www/moodle/2.8.6/blocks/course_status_tracker/block_course_status_tracker.php on line 110

Have addressed the issue locally changing line 110 from

`$this->content->text .= get_string('enrolled_courses', 'block_course_status_tracker') . " :	<b>" . $link_enrolled_courses . "</b><br>";`

to

`$this->content->text = get_string('enrolled_courses', 'block_course_status_tracker') . " :	<b>" . $link_enrolled_courses . "</b><br>";`

**Comment by 3ilogiclms** [comment]
Dear guyfugacity,
We actually found notice on line number 143 and removed it.
 "Trying to get property of non-object on lib.php on line 143"

Thanks for identify issue

Regards,
3i Logic LMS
